---
- name: Gluu - Get LDAP Admin password
  command: 'grep -oP "ldapPass=\K(.+)" /opt/gluu-server-{{ gluu_version }}/install/community-edition-setup/setup.properties.last'
  register: gluu_ldap_admin_password

- name: Gluu - Get JDK Path
  command: 'grep -oP "jreDestinationPath=\K(.+)" /opt/gluu-server-{{ gluu_version }}/install/community-edition-setup/setup.properties.last'
  register: gluu_jdk_path

- name: Gluu - Get cert store password
  command: 'grep -oP "^openldapJksPass=\K(.+)" /opt/gluu-server-{{ gluu_version }}/install/community-edition-setup/setup.properties.last'
  register: gluu_ldap_cert_store_password

