---

# Parameters
- name: Include variables.
  include_vars: "all.yml"

# Variable setup
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: soft.yml

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install global python requirements
  pip:
    state: present
    name:
      - dpath
      - pyDes
      - python-ldap
      - ldap3

- include: gluu-setup.yml

- include: gluu-get-configuration.yml


#- name: Update etc/hosts
#  lineinfile:
#    path: /etc/hosts
#    state: present
#    regexp: '{{server_ip_pattern}}'
#    line: '{{server_ip}}  {{server_hostname}}'

