---
- name: Add ubuntu universe repo
  command: add-apt-repository universe

- name: Update and upgrade apt packages
  apt:
      upgrade: yes
      update_cache: yes
      #cache_valid_time: 86400 #One day

- name: Install curl
  apt:
      name: curl
      state: present

- name: Install mc
  apt:
      name: mc
      state: present